### PR TITLE
Pull security patch to Feature A1

### PR DESCRIPTION
**Pull request by coolvasdev**
Pulling latest security patches to Feature A1 branch

### CODE REVIEW

**Comment by dreddy22** [comment]
Updating Feature A1 branch

**Comment by muduli86** [comment]
review

**Comment by saikumar30421** [comment]
https://github.com/saikumar30421/merge-conflict.git

**Comment by vivekkalbhore** [comment]
changes one

**Comment by vijaigopal** [comment]
Update feature 1 and feature 2 on master of my git hub

**Comment by sarathveyron** [comment]
Pulling latest security patches to Feature A1 branch

**Comment by Anusha-anus** [comment]
review

**Comment by aartiamin701** [comment]
review

**Comment by jainendrapathak-home** [comment]
please merge pull request.

**Comment by wasim0028** [comment]
Add security patch in feature2 branch

**Pull request closed without merging**
